export const jsondata = [
    {
        "cost_code": "030000",
        "name": "Concrete",
        "Original Budget Amount": 13988286,
        "Budget Modifications": 0,
        "Approved COs": 791374.25,
        "Revised Budget": 14779660.25,
        "Pending Budget Changes": 0,
        "Projected Budget": 14779660.25,
        "Committed Costs": 14592719.71,
        "Direct Costs": 0,
        "Pending Cost Changes": 0,
        "Projected Costs": 14592719.71,
        "Forecast To Complete": 186940.54,
        "Estimated Cost at Completion": 14779660.25,
        "Projected over Under": 0,
        "Requistitions Net Actuals": 8825095.38
    },
    {
        "cost_code": "033100",
        "name": "Site Utilities",
        "Original Budget Amount": 0,
        "Budget Modifications": 0,
        "Approved COs": 0,
        "Revised Budget": 0,
        "Pending Budget Changes": 0,
        "Projected Budget": 0,
        "Committed Costs": 0,
        "Direct Costs": 0,
        "Pending Cost Changes": 0,
        "Projected Costs": 0,
        "Forecast To Complete": 0,
        "Estimated Cost at Completion": 0,
        "Projected over Under": 0,
        "Requistitions Net Actuals": 0
    },
    {
        "cost_code": "035400",
        "name": "Cast Underlayment",
        "Original Budget Amount": 716293,
        "Budget Modifications": 0,
        "Approved COs": 0,
        "Revised Budget": 716293,
        "Pending Budget Changes": 0,
        "Projected Budget": 716293,
        "Committed Costs": 0,
        "Direct Costs": 0,
        "Pending Cost Changes": 0,
        "Projected Costs": 0,
        "Forecast To Complete": 716293,
        "Estimated Cost at Completion": 716293,
        "Projected over Under": 0,
        "Requistitions Net Actuals": 0
    },
    {
        "cost_code": "040000",
        "name": "Masonry",
        "Original Budget Amount": 777989,
        "Budget Modifications": 0,
        "Approved COs": 72624,
        "Revised Budget": 850613,
        "Pending Budget Changes": 0,
        "Projected Budget": 850613,
        "Committed Costs": 133163.95,
        "Direct Costs": 0,
        "Pending Cost Changes": 0,
        "Projected Costs": 133163.95,
        "Forecast To Complete": 717449.05,
        "Estimated Cost at Completion": 850613,
        "Projected over Under": 0,
        "Requistitions Net Actuals": 121370
    },
    {
        "cost_code": "050000",
        "name": "Metals",
        "Original Budget Amount": 1498181,
        "Budget Modifications": 0,
        "Approved COs": 26000,
        "Revised Budget": 1524181,
        "Pending Budget Changes": 0,
        "Projected Budget": 1524181,
        "Committed Costs": 1972939.46,
        "Direct Costs": 0,
        "Pending Cost Changes": 0,
        "Projected Costs": 1972939.46,
        "Forecast To Complete": 0,
        "Estimated Cost at Completion": 1972939.46,
        "Projected over Under": -448758.46,
        "Requistitions Net Actuals": 130868.6
    },
    {
        "cost_code": "061000",
        "name": "Rough Carpentry",
        "Original Budget Amount": 0,
        "Budget Modifications": 655305,
        "Approved COs": 0,
        "Revised Budget": 655305,
        "Pending Budget Changes": 0,
        "Projected Budget": 655305,
        "Committed Costs": 655305,
        "Direct Costs": 0,
        "Pending Cost Changes": 0,
        "Projected Costs": 655305,
        "Forecast To Complete": 0,
        "Estimated Cost at Completion": 655305,
        "Projected over Under": 0,
        "Requistitions Net Actuals": 35350
    },
    {
        "cost_code": "061200",
        "name": "Structural Panels",
        "Original Budget Amount": 6206785,
        "Budget Modifications": -655305,
        "Approved COs": 0,
        "Revised Budget": 5551480,
        "Pending Budget Changes": 0,
        "Projected Budget": 5551480,
        "Committed Costs": 0,
        "Direct Costs": 0,
        "Pending Cost Changes": 0,
        "Projected Costs": 0,
        "Forecast To Complete": 5551480,
        "Estimated Cost at Completion": 5551480,
        "Projected over Under": 0,
        "Requistitions Net Actuals": 0
    },
    {
        "cost_code": "064600",
        "name": "Wood Trim",
        "Original Budget Amount": 1103425,
        "Budget Modifications": 0,
        "Approved COs": 0,
        "Revised Budget": 1103425,
        "Pending Budget Changes": 0,
        "Projected Budget": 1103425,
        "Committed Costs": 0,
        "Direct Costs": 0,
        "Pending Cost Changes": 0,
        "Projected Costs": 0,
        "Forecast To Complete": 1103425,
        "Estimated Cost at Completion": 1103425,
        "Projected over Under": 0,
        "Requistitions Net Actuals": 0
    },
    {
        "cost_code": "071000",
        "name": "Dampproofing & Waterproofing",
        "Original Budget Amount": 1249549,
        "Budget Modifications": 0,
        "Approved COs": 0,
        "Revised Budget": 1249549,
        "Pending Budget Changes": 0,
        "Projected Budget": 1249549,
        "Committed Costs": 530000,
        "Direct Costs": 0,
        "Pending Cost Changes": 0,
        "Projected Costs": 530000,
        "Forecast To Complete": 719549,
        "Estimated Cost at Completion": 1249549,
        "Projected over Under": 0,
        "Requistitions Net Actuals": 107300
    },
    {
        "cost_code": "073000",
        "name": "General Roofing",
        "Original Budget Amount": 1322662,
        "Budget Modifications": 0,
        "Approved COs": 0,
        "Revised Budget": 1322662,
        "Pending Budget Changes": 0,
        "Projected Budget": 1322662,
        "Committed Costs": 0,
        "Direct Costs": 0,
        "Pending Cost Changes": 0,
        "Projected Costs": 0,
        "Forecast To Complete": 1425000,
        "Estimated Cost at Completion": 1425000,
        "Projected over Under": -102338,
        "Requistitions Net Actuals": 0
    },
    {
        "cost_code": "081000",
        "name": "Doors & Frames",
        "Original Budget Amount": 3330463,
        "Budget Modifications": 0,
        "Approved COs": 0,
        "Revised Budget": 3330463,
        "Pending Budget Changes": 0,
        "Projected Budget": 3330463,
        "Committed Costs": 15214.16,
        "Direct Costs": 0,
        "Pending Cost Changes": 0,
        "Projected Costs": 15214.16,
        "Forecast To Complete": 3315248.84,
        "Estimated Cost at Completion": 3330463,
        "Projected over Under": 0,
        "Requistitions Net Actuals": 8210.7
    },
    {
        "cost_code": "092000",
        "name": "Plaster & Gypsum Board",
        "Original Budget Amount": 5354462,
        "Budget Modifications": 0,
        "Approved COs": 0,
        "Revised Budget": 5354462,
        "Pending Budget Changes": 0,
        "Projected Budget": 5354462,
        "Committed Costs": 0,
        "Direct Costs": 0,
        "Pending Cost Changes": 0,
        "Projected Costs": 0,
        "Forecast To Complete": 6354462,
        "Estimated Cost at Completion": 6354462,
        "Projected over Under": -1000000,
        "Requistitions Net Actuals": 0
    },
    {
        "cost_code": "096000",
        "name": "Flooring",
        "Original Budget Amount": 839277,
        "Budget Modifications": 0,
        "Approved COs": 0,
        "Revised Budget": 839277,
        "Pending Budget Changes": 0,
        "Projected Budget": 839277,
        "Committed Costs": 0,
        "Direct Costs": 0,
        "Pending Cost Changes": 0,
        "Projected Costs": 0,
        "Forecast To Complete": 839277,
        "Estimated Cost at Completion": 839277,
        "Projected over Under": 0,
        "Requistitions Net Actuals": 0
    },
    {
        "cost_code": "099000",
        "name": "Painting & Coatings",
        "Original Budget Amount": 731557,
        "Budget Modifications": 0,
        "Approved COs": 0,
        "Revised Budget": 731557,
        "Pending Budget Changes": 0,
        "Projected Budget": 731557,
        "Committed Costs": 0,
        "Direct Costs": 0,
        "Pending Cost Changes": 0,
        "Projected Costs": 0,
        "Forecast To Complete": 731557,
        "Estimated Cost at Completion": 731557,
        "Projected over Under": 0,
        "Requistitions Net Actuals": 0
    },
    {
        "cost_code": "100000",
        "name": "Specialties",
        "Original Budget Amount": 222971,
        "Budget Modifications": 0,
        "Approved COs": 0,
        "Revised Budget": 222971,
        "Pending Budget Changes": 0,
        "Projected Budget": 222971,
        "Committed Costs": 0,
        "Direct Costs": 0,
        "Pending Cost Changes": 0,
        "Projected Costs": 0,
        "Forecast To Complete": 222971,
        "Estimated Cost at Completion": 222971,
        "Projected over Under": 0,
        "Requistitions Net Actuals": 0
    },
    {
        "cost_code": "105500",
        "name": "Postal Specialties",
        "Original Budget Amount": 44625,
        "Budget Modifications": 0,
        "Approved COs": 0,
        "Revised Budget": 44625,
        "Pending Budget Changes": 0,
        "Projected Budget": 44625,
        "Committed Costs": 0,
        "Direct Costs": 0,
        "Pending Cost Changes": 0,
        "Projected Costs": 0,
        "Forecast To Complete": 44625,
        "Estimated Cost at Completion": 44625,
        "Projected over Under": 0,
        "Requistitions Net Actuals": 0
    },
    {
        "cost_code": "110000",
        "name": "Equipment",
        "Original Budget Amount": 0,
        "Budget Modifications": 0,
        "Approved COs": 0,
        "Revised Budget": 0,
        "Pending Budget Changes": 0,
        "Projected Budget": 0,
        "Committed Costs": 0,
        "Direct Costs": 0,
        "Pending Cost Changes": 0,
        "Projected Costs": 0,
        "Forecast To Complete": 0,
        "Estimated Cost at Completion": 0,
        "Projected over Under": 0,
        "Requistitions Net Actuals": 0
    },
    {
        "cost_code": "113013",
        "name": "Residential Appliances",
        "Original Budget Amount": 1166373,
        "Budget Modifications": 0,
        "Approved COs": 0,
        "Revised Budget": 1166373,
        "Pending Budget Changes": 0,
        "Projected Budget": 1166373,
        "Committed Costs": 0,
        "Direct Costs": 0,
        "Pending Cost Changes": 0,
        "Projected Costs": 0,
        "Forecast To Complete": 1166373,
        "Estimated Cost at Completion": 1166373,
        "Projected over Under": 0,
        "Requistitions Net Actuals": 0
    },
    {
        "cost_code": "120000",
        "name": "Furnishings",
        "Original Budget Amount": 353042,
        "Budget Modifications": 0,
        "Approved COs": 0,
        "Revised Budget": 353042,
        "Pending Budget Changes": 0,
        "Projected Budget": 353042,
        "Committed Costs": 0,
        "Direct Costs": 0,
        "Pending Cost Changes": 0,
        "Projected Costs": 0,
        "Forecast To Complete": 353042,
        "Estimated Cost at Completion": 353042,
        "Projected over Under": 0,
        "Requistitions Net Actuals": 0
    },
    {
        "cost_code": "122000",
        "name": "Window Treatments",
        "Original Budget Amount": 159300,
        "Budget Modifications": 0,
        "Approved COs": 0,
        "Revised Budget": 159300,
        "Pending Budget Changes": 0,
        "Projected Budget": 159300,
        "Committed Costs": 0,
        "Direct Costs": 0,
        "Pending Cost Changes": 0,
        "Projected Costs": 0,
        "Forecast To Complete": 159300,
        "Estimated Cost at Completion": 159300,
        "Projected over Under": 0,
        "Requistitions Net Actuals": 0
    },
    {
        "cost_code": "130000",
        "name": "Special Construction",
        "Original Budget Amount": 342709,
        "Budget Modifications": 0,
        "Approved COs": 0,
        "Revised Budget": 342709,
        "Pending Budget Changes": 0,
        "Projected Budget": 342709,
        "Committed Costs": 0,
        "Direct Costs": 0,
        "Pending Cost Changes": 0,
        "Projected Costs": 0,
        "Forecast To Complete": 342709,
        "Estimated Cost at Completion": 342709,
        "Projected over Under": 0,
        "Requistitions Net Actuals": 0
    },
    {
        "cost_code": "140000",
        "name": "Conveying Equipment",
        "Original Budget Amount": 823920,
        "Budget Modifications": 0,
        "Approved COs": 0,
        "Revised Budget": 823920,
        "Pending Budget Changes": 0,
        "Projected Budget": 823920,
        "Committed Costs": 1233099.8,
        "Direct Costs": 0,
        "Pending Cost Changes": 0,
        "Projected Costs": 1233099.8,
        "Forecast To Complete": 124800,
        "Estimated Cost at Completion": 1357899.8,
        "Projected over Under": -533979.8,
        "Requistitions Net Actuals": 22221.4
    },
    {
        "cost_code": "210000",
        "name": "Fire Sprinkers/Suppression",
        "Original Budget Amount": 1769825,
        "Budget Modifications": -559311,
        "Approved COs": 0,
        "Revised Budget": 1210514,
        "Pending Budget Changes": 0,
        "Projected Budget": 1210514,
        "Committed Costs": 1226776,
        "Direct Costs": 0,
        "Pending Cost Changes": 0,
        "Projected Costs": 1226776,
        "Forecast To Complete": 0,
        "Estimated Cost at Completion": 1226776,
        "Projected over Under": -16262,
        "Requistitions Net Actuals": 87491.7
    },
    {
        "cost_code": "210001",
        "name": "Fire Alarm",
        "Original Budget Amount": 0,
        "Budget Modifications": 559311,
        "Approved COs": 194029,
        "Revised Budget": 753340,
        "Pending Budget Changes": 0,
        "Projected Budget": 753340,
        "Committed Costs": 753340,
        "Direct Costs": 0,
        "Pending Cost Changes": 0,
        "Projected Costs": 753340,
        "Forecast To Complete": 0,
        "Estimated Cost at Completion": 753340,
        "Projected over Under": 0,
        "Requistitions Net Actuals": 62857
    },
    {
        "cost_code": "220000",
        "name": "Plumbing",
        "Original Budget Amount": 4975450,
        "Budget Modifications": 0,
        "Approved COs": 0,
        "Revised Budget": 4975450,
        "Pending Budget Changes": 0,
        "Projected Budget": 4975450,
        "Committed Costs": 274099.78,
        "Direct Costs": 0,
        "Pending Cost Changes": 0,
        "Projected Costs": 274099.78,
        "Forecast To Complete": 4701350.22,
        "Estimated Cost at Completion": 4975450,
        "Projected over Under": 0,
        "Requistitions Net Actuals": 181110.78
    },
    {
        "cost_code": "230000",
        "name": "Heating Ventilating & AC (HVAC)",
        "Original Budget Amount": 3743786,
        "Budget Modifications": 0,
        "Approved COs": 134835,
        "Revised Budget": 3878621,
        "Pending Budget Changes": 0,
        "Projected Budget": 3878621,
        "Committed Costs": 275635,
        "Direct Costs": 0,
        "Pending Cost Changes": 0,
        "Projected Costs": 275635,
        "Forecast To Complete": 3602986,
        "Estimated Cost at Completion": 3878621,
        "Projected over Under": 0,
        "Requistitions Net Actuals": 0
    },
    {
        "cost_code": "260000",
        "name": "Electrical",
        "Original Budget Amount": 4560734,
        "Budget Modifications": 0,
        "Approved COs": 0,
        "Revised Budget": 4560734,
        "Pending Budget Changes": 0,
        "Projected Budget": 4560734,
        "Committed Costs": 4017588,
        "Direct Costs": 0,
        "Pending Cost Changes": 0,
        "Projected Costs": 4017588,
        "Forecast To Complete": 1804885,
        "Estimated Cost at Completion": 5822473,
        "Projected over Under": -1261739,
        "Requistitions Net Actuals": 142381.86
    },
    {
        "cost_code": "310000",
        "name": "Earthwork",
        "Original Budget Amount": 3154207,
        "Budget Modifications": 0,
        "Approved COs": 165140.07,
        "Revised Budget": 3319347.07,
        "Pending Budget Changes": 0,
        "Projected Budget": 3319347.07,
        "Committed Costs": 2694081,
        "Direct Costs": 0,
        "Pending Cost Changes": 0,
        "Projected Costs": 2694081,
        "Forecast To Complete": 518408,
        "Estimated Cost at Completion": 3212489,
        "Projected over Under": 106858.07,
        "Requistitions Net Actuals": 1383607.25
    },
    {
        "cost_code": "329000",
        "name": "Planting",
        "Original Budget Amount": 1404749,
        "Budget Modifications": 0,
        "Approved COs": 0,
        "Revised Budget": 1404749,
        "Pending Budget Changes": 0,
        "Projected Budget": 1404749,
        "Committed Costs": 0,
        "Direct Costs": 0,
        "Pending Cost Changes": 0,
        "Projected Costs": 0,
        "Forecast To Complete": 1404749,
        "Estimated Cost at Completion": 1404749,
        "Projected over Under": 0,
        "Requistitions Net Actuals": 0
    },
    {
        "cost_code": "910000",
        "name": "Construction Fee",
        "Original Budget Amount": 2293947,
        "Budget Modifications": 0,
        "Approved COs": 55360.11,
        "Revised Budget": 2349307.11,
        "Pending Budget Changes": 0,
        "Projected Budget": 2349307.11,
        "Committed Costs": 0,
        "Direct Costs": 0,
        "Pending Cost Changes": 0,
        "Projected Costs": 0,
        "Forecast To Complete": 0,
        "Estimated Cost at Completion": 0,
        "Projected over Under": 2349307.11,
        "Requistitions Net Actuals": 0
    },
    {
        "cost_code": "920000",
        "name": "Construction Contingency",
        "Original Budget Amount": 2532922,
        "Budget Modifications": 0,
        "Approved COs": -103707.5,
        "Revised Budget": 2429214.5,
        "Pending Budget Changes": 0,
        "Projected Budget": 2429214.5,
        "Committed Costs": 0,
        "Direct Costs": 0,
        "Pending Cost Changes": 0,
        "Projected Costs": 0,
        "Forecast To Complete": 0,
        "Estimated Cost at Completion": 0,
        "Projected over Under": 2429214.5,
        "Requistitions Net Actuals": 0
    },
    {
        "cost_code": "992000",
        "name": "Logistics",
        "Original Budget Amount": 274200,
        "Budget Modifications": 0,
        "Approved COs": 0,
        "Revised Budget": 274200,
        "Pending Budget Changes": 0,
        "Projected Budget": 274200,
        "Committed Costs": 0,
        "Direct Costs": 0,
        "Pending Cost Changes": 0,
        "Projected Costs": 0,
        "Forecast To Complete": 0,
        "Estimated Cost at Completion": 0,
        "Projected over Under": 274200,
        "Requistitions Net Actuals": 0
    }
];
